import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Navbar/themes/provider";
import dynamic from 'next/dynamic';
import { Suspense } from "react";

const Sidebar = dynamic(() => import('@/components/sidebar/Sidebar'), { ssr: false });
const Navbar = dynamic(() => import('@/components/Navbar/Navbar'), { ssr: false });


const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Venkatesh-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} bg-background bg-no-repeat md:h-[115rem] lg:h-[70rem] dark:bg-background-dark`}>
        <Providers>
          <div className="h-[110vh] flex flex-col">
            <Navbar />
            <div className="flex flex-1">
              <Sidebar />
              <main className="flex-1">
                
                  {children}
               
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
